### ISSUE TITLE
Keyboard module requires administrative privileges with OS X

### ISSUE THREAD

**Issue by cthil** [benjamindrayer/arcade#9]
As of using the keyboard module, the game doesn't run on OS X anymore as user. The documentation describes this as a security limitation (btw, same for Linux).

```
pygame 2.0.1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
FlexChainGame set-up and ready to go
Exception in thread Thread-1:
Traceback (most recent call last):
  File "Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "~/Library/Python/3.9/lib/python/site-packages/keyboard/__init__.py", line 294, in listen
    _os_keyboard.listen(self.direct_callback)
  File "~/Library/Python/3.9/lib/python/site-packages/keyboard/_darwinkeyboard.py", line 430, in listen
    raise OSError("Error 13 - Must be run as administrator")
OSError: Error 13 - Must be run as administrator
```

Could you please include the "legacy" keyboard monitoring code?

**Comment by benjamindrayer** [comment]
Good point. The library for the rgb-display does also require root-priveliges. With the main application (rgb-disaplay + raspberry pi) in mind I thought, that we run it as root anyway... But I agree that it fells painful to need root privs to read out the keyboard. 

Under Linux, the keyboard package reads the files in /dev/input/... and therefore it needs to be root. I'll rethink it... Thanks for the feedback.

**Comment by benjamindrayer** [comment]
I tried to make the pygame-keyboard reading work in the new design, but the main problem was that the pygame events (including the keyboard events) do only work in the main thread. The communication with the flexchain and also the reading of the keyboard runs in a seperate background thread... I might have a look in the pynput package, that seems to run without root privs.

**Comment by benjamindrayer** [comment]
I just had a look at the homepage: https://pynput.readthedocs.io/en/latest/limitations.html and it looks like the package works for windows and linux, but "Recent versions of macOS restrict monitoring of the keyboard for security reasons", so you probably need root privs again...

**Comment by cthil** [comment]
I tried pynput on OS X and it (partially) works as regular user, if the interpreter/terminal app is whitelisted in System Preferences (as described in the docs).
But so far, my test script captures 'special keys' like <ctrl> or <alt> :( Could you please try the attached script? If it works, I'd be fine with pynput to capture the keyboard (but I still need to capture alphanumeric keys).

```
#!/usr/bin/env python3

from pynput import keyboard
import time

def on_press(key):
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
    except AttributeError:
        print('special key {0} pressed'.format(
            key))

def on_release(key):
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        return False

# Collect events until released
#with keyboard.Listener(
#        on_press=on_press,
#        on_release=on_release) as listener:
#    listener.join()

# ...or, in a non-blocking fashion:
listener = keyboard.Listener(
    on_press=on_press,
    on_release=on_release)
listener.start()

while True:
    # do something
    print(".")
    time.sleep(1)
```
